# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-09-19 06:40
from __future__ import unicode_literals

from django.db import migrations

def create_initial_authors(apps, schema_editor):
    Author = apps.get_model('api', 'Author')

    Author(first_name='RIIS', last_name='ASSHOLE').save()
    Author(first_name='Jeremy', last_name='Daddy').save()
    Author(first_name='Leatitia', last_name='RandomEu').save()


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_initial_authors),
    ]
