# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-11-13 06:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='image',
            field=models.ImageField(default='../user.png', upload_to=''),
        ),
    ]
