# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-11-15 10:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_book_rent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rent',
            old_name='status',
            new_name='returned',
        ),
    ]
